#ifndef ENVE_FFMPEG_COMPAT_H
#define ENVE_FFMPEG_COMPAT_H

extern "C" {
    #include <libavutil/version.h>
    #include <libavutil/channel_layout.h>
}

// FFmpeg 7.0+ removed AV_CH_LAYOUT_* macros (FF_API_OLD_CHANNEL_LAYOUT)
// This header provides compatibility shims for FFmpeg 6.x/7.x/8.x

#if LIBAVUTIL_VERSION_INT >= AV_VERSION_INT(59, 0, 0)
// FFmpeg 7.0+: AV_CH_LAYOUT_* macros removed, define them from AVChannelLayout constants

#ifndef AV_CH_LAYOUT_MONO
#define AV_CH_LAYOUT_MONO AV_CH_FRONT_CENTER
#endif

#ifndef AV_CH_LAYOUT_STEREO
#define AV_CH_LAYOUT_STEREO (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT)
#endif

#ifndef AV_CH_LAYOUT_2POINT1
#define AV_CH_LAYOUT_2POINT1 (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_LOW_FREQUENCY)
#endif

#ifndef AV_CH_LAYOUT_SURROUND
#define AV_CH_LAYOUT_SURROUND (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER)
#endif

#ifndef AV_CH_LAYOUT_2_1
#define AV_CH_LAYOUT_2_1 (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_BACK_CENTER)
#endif

#ifndef AV_CH_LAYOUT_4POINT0
#define AV_CH_LAYOUT_4POINT0 (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_BACK_CENTER)
#endif

#ifndef AV_CH_LAYOUT_QUAD
#define AV_CH_LAYOUT_QUAD (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_BACK_LEFT|AV_CH_BACK_RIGHT)
#endif

#ifndef AV_CH_LAYOUT_2_2
#define AV_CH_LAYOUT_2_2 (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_SIDE_LEFT|AV_CH_SIDE_RIGHT)
#endif

#ifndef AV_CH_LAYOUT_3POINT1
#define AV_CH_LAYOUT_3POINT1 (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_LOW_FREQUENCY)
#endif

#ifndef AV_CH_LAYOUT_5POINT0_BACK
#define AV_CH_LAYOUT_5POINT0_BACK (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_BACK_LEFT|AV_CH_BACK_RIGHT)
#endif

#ifndef AV_CH_LAYOUT_5POINT0
#define AV_CH_LAYOUT_5POINT0 (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_SIDE_LEFT|AV_CH_SIDE_RIGHT)
#endif

#ifndef AV_CH_LAYOUT_4POINT1
#define AV_CH_LAYOUT_4POINT1 (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_LOW_FREQUENCY|AV_CH_BACK_CENTER)
#endif

#ifndef AV_CH_LAYOUT_5POINT1_BACK
#define AV_CH_LAYOUT_5POINT1_BACK (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_LOW_FREQUENCY|AV_CH_BACK_LEFT|AV_CH_BACK_RIGHT)
#endif

#ifndef AV_CH_LAYOUT_5POINT1
#define AV_CH_LAYOUT_5POINT1 (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_LOW_FREQUENCY|AV_CH_SIDE_LEFT|AV_CH_SIDE_RIGHT)
#endif

#ifndef AV_CH_LAYOUT_6POINT0
#define AV_CH_LAYOUT_6POINT0 (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_BACK_LEFT|AV_CH_BACK_RIGHT|AV_CH_BACK_CENTER)
#endif

#ifndef AV_CH_LAYOUT_6POINT0_FRONT
#define AV_CH_LAYOUT_6POINT0_FRONT (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_SIDE_LEFT|AV_CH_SIDE_RIGHT|AV_CH_BACK_CENTER)
#endif

#ifndef AV_CH_LAYOUT_HEXAGONAL
#define AV_CH_LAYOUT_HEXAGONAL (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_BACK_LEFT|AV_CH_BACK_RIGHT|AV_CH_BACK_CENTER)
#endif

#ifndef AV_CH_LAYOUT_6POINT1
#define AV_CH_LAYOUT_6POINT1 (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_LOW_FREQUENCY|AV_CH_BACK_LEFT|AV_CH_BACK_RIGHT|AV_CH_BACK_CENTER)
#endif

#ifndef AV_CH_LAYOUT_6POINT1_BACK
#define AV_CH_LAYOUT_6POINT1_BACK AV_CH_LAYOUT_6POINT1
#endif

#ifndef AV_CH_LAYOUT_6POINT1_FRONT
#define AV_CH_LAYOUT_6POINT1_FRONT (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_LOW_FREQUENCY|AV_CH_SIDE_LEFT|AV_CH_SIDE_RIGHT|AV_CH_BACK_CENTER)
#endif

#ifndef AV_CH_LAYOUT_7POINT0
#define AV_CH_LAYOUT_7POINT0 (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_BACK_LEFT|AV_CH_BACK_RIGHT|AV_CH_SIDE_LEFT|AV_CH_SIDE_RIGHT)
#endif

#ifndef AV_CH_LAYOUT_7POINT0_FRONT
#define AV_CH_LAYOUT_7POINT0_FRONT (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_SIDE_LEFT|AV_CH_SIDE_RIGHT|AV_CH_FRONT_LEFT_OF_CENTER|AV_CH_FRONT_RIGHT_OF_CENTER)
#endif

#ifndef AV_CH_LAYOUT_7POINT1
#define AV_CH_LAYOUT_7POINT1 (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_LOW_FREQUENCY|AV_CH_BACK_LEFT|AV_CH_BACK_RIGHT|AV_CH_SIDE_LEFT|AV_CH_SIDE_RIGHT)
#endif

#ifndef AV_CH_LAYOUT_7POINT1_WIDE_BACK
#define AV_CH_LAYOUT_7POINT1_WIDE_BACK (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_LOW_FREQUENCY|AV_CH_BACK_LEFT|AV_CH_BACK_RIGHT|AV_CH_FRONT_LEFT_OF_CENTER|AV_CH_FRONT_RIGHT_OF_CENTER)
#endif

#ifndef AV_CH_LAYOUT_7POINT1_WIDE
#define AV_CH_LAYOUT_7POINT1_WIDE AV_CH_LAYOUT_7POINT1
#endif

#ifndef AV_CH_LAYOUT_OCTAGONAL
#define AV_CH_LAYOUT_OCTAGONAL (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_BACK_LEFT|AV_CH_BACK_RIGHT|AV_CH_SIDE_LEFT|AV_CH_SIDE_RIGHT|AV_CH_BACK_CENTER)
#endif

#ifndef AV_CH_LAYOUT_HEXADECAGONAL
#define AV_CH_LAYOUT_HEXADECAGONAL (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT|AV_CH_FRONT_CENTER|AV_CH_BACK_LEFT|AV_CH_BACK_RIGHT|AV_CH_SIDE_LEFT|AV_CH_SIDE_RIGHT|AV_CH_BACK_CENTER|AV_CH_TOP_FRONT_LEFT|AV_CH_TOP_FRONT_RIGHT|AV_CH_TOP_FRONT_CENTER|AV_CH_TOP_BACK_LEFT|AV_CH_TOP_BACK_RIGHT|AV_CH_TOP_BACK_CENTER)
#endif

#ifndef AV_CH_LAYOUT_STEREO_DOWNMIX
#define AV_CH_LAYOUT_STEREO_DOWNMIX (AV_CH_STEREO_LEFT|AV_CH_STEREO_RIGHT)
#endif

// Additional channel constants that may be missing
#ifndef AV_CH_FRONT_LEFT_OF_CENTER
#define AV_CH_FRONT_LEFT_OF_CENTER (1ULL << 16)
#endif

#ifndef AV_CH_FRONT_RIGHT_OF_CENTER
#define AV_CH_FRONT_RIGHT_OF_CENTER (1ULL << 17)
#endif

#ifndef AV_CH_BACK_CENTER
#define AV_CH_BACK_CENTER (1ULL << 18)
#endif

#ifndef AV_CH_SIDE_LEFT
#define AV_CH_SIDE_LEFT (1ULL << 19)
#endif

#ifndef AV_CH_SIDE_RIGHT
#define AV_CH_SIDE_RIGHT (1ULL << 20)
#endif

#ifndef AV_CH_TOP_CENTER
#define AV_CH_TOP_CENTER (1ULL << 21)
#endif

#ifndef AV_CH_TOP_FRONT_LEFT
#define AV_CH_TOP_FRONT_LEFT (1ULL << 22)
#endif

#ifndef AV_CH_TOP_FRONT_CENTER
#define AV_CH_TOP_FRONT_CENTER (1ULL << 23)
#endif

#ifndef AV_CH_TOP_FRONT_RIGHT
#define AV_CH_TOP_FRONT_RIGHT (1ULL << 24)
#endif

#ifndef AV_CH_TOP_BACK_LEFT
#define AV_CH_TOP_BACK_LEFT (1ULL << 25)
#endif

#ifndef AV_CH_TOP_BACK_CENTER
#define AV_CH_TOP_BACK_CENTER (1ULL << 26)
#endif

#ifndef AV_CH_TOP_BACK_RIGHT
#define AV_CH_TOP_BACK_RIGHT (1ULL << 27)
#endif

#ifndef AV_CH_STEREO_LEFT
#define AV_CH_STEREO_LEFT (1ULL << 29)
#endif

#ifndef AV_CH_STEREO_RIGHT
#define AV_CH_STEREO_RIGHT (1ULL << 30)
#endif

#ifndef AV_CH_WIDE_LEFT
#define AV_CH_WIDE_LEFT (1ULL << 31)
#endif

#ifndef AV_CH_WIDE_RIGHT
#define AV_CH_WIDE_RIGHT (1ULL << 32)
#endif

#ifndef AV_CH_LOW_FREQUENCY_2
#define AV_CH_LOW_FREQUENCY_2 (1ULL << 35)
#endif

#endif // LIBAVUTIL_VERSION_INT >= AV_VERSION_INT(59, 0, 0)

// Unified ENVE_AV_GET_CHANNEL_LAYOUT_NB_CHANNELS macro for all FFmpeg versions
// FFmpeg 6.x+: AVChannelLayout struct with .nb_channels field
// FFmpeg 4.x/5.x: uint64_t mask, use av_get_channel_layout_nb_channels()
#if LIBAVUTIL_VERSION_INT >= AV_VERSION_INT(57, 49, 100)
#define ENVE_AV_GET_CHANNEL_LAYOUT_NB_CHANNELS(layout) \
    ((layout).nb_channels)
#else
#define ENVE_AV_GET_CHANNEL_LAYOUT_NB_CHANNELS(layout) \
    av_get_channel_layout_nb_channels(layout)
#endif

// FFmpeg 7.0+ removed av_get_channel_layout_nb_channels(uint64_t)
// Provide inline compat shim for code that still uses uint64_t layout masks
#if LIBAVUTIL_VERSION_INT >= AV_VERSION_INT(59, 0, 0)
static inline int enve_av_channel_layout_nb_channels_from_mask(uint64_t layout) {
    AVChannelLayout ch;
    av_channel_layout_from_mask(&ch, layout);
    return ch.nb_channels;
}
#define av_get_channel_layout_nb_channels(layout) \
    enve_av_channel_layout_nb_channels_from_mask(layout)
#endif

#endif // ENVE_FFMPEG_COMPAT_H
